# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fe4a34ca2e881ccd1f178218950aaf04f1c150f03a65afa162100d856b89c6559b8f9957b8e394f696a312d7a2212a094095fcd395fce219db168ae88fa5f94

test:
  secret_key_base: 457ac1c923c6b06ce938f3cf12359added60730fb020d3fc266c13bdeaa0d51c76e65e9017797d2acb4e5e47a86a32293efdbd7caad9d26f162356909be189a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
